name: $hyoo_lupa

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'hyoo/lupa'
    
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'hyoo/lupa/-' #FIXME path to build app
    
    - uses: koplenov/web-to-app-action@main
      with:
          build-folder-path: 'hyoo/lupa/-' # Defaults to build, It is the folder where build files or html are stored
          app-name: 'lupa.hyoo.ru' # Defaults to MyApp
          output-folder-path: 'my-apks' # Defaults to apk/, Where final APK files are created
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: Final-apks
        path: my-apks/ # Should be same as "output-folder-path"
