name: $hyoo_lupa

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'hyoo/lupa'
    
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'hyoo/lupa/-' #FIXME path to build app
    
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        java-version: 8
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8

    - name: Build
      run: |
        ionic cordova build android --prod

